# Generated by Django 2.1.1 on 2019-04-30 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0002_captions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='captions',
            name='img',
        ),
        migrations.RemoveField(
            model_name='commentimage',
            name='img',
        ),
        migrations.AddField(
            model_name='commentimage',
            name='img_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='caption',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.DeleteModel(
            name='Captions',
        ),
    ]
