# Generated by Django 2.1.1 on 2019-05-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0003_auto_20190501_0326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_id', models.IntegerField(default=0)),
                ('like', models.IntegerField(default=0)),
            ],
        ),
    ]
